language: python
python:
  - 3.8
  - 3.7
  - 3.6
 - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: opencdms_process
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: opencdms_process/opencdms_process
    python: 3.8

env:
  global:
    secure: azaHN4/dmUTSowSc4dvmGVvb4SVdMck+7lkRLtJGPzwfQl6dg0PwKZcnCKi42GHBf7ljgBXxBVc6Q87Gfpb1Ig3prME2EhWu0PU6M5CMVUXS3hJshnsTgdQfitzf+hNKiSXhLemhDVix8DPbUjmIfThVRvuPXZmU1PfdobmAgYbheuyW4prb9jbBuwrjVkv6iS/8Vt/a3hliUiSULIMv03QgpeBxQDgjCNXIhR2IpP9YWSeFY4FppCmciiTERKXrqFeNjj2dYuknNkYgpgfWa0iLOkhF9udRMmnEU4vVFE52teaEvvgMlaZUKHGKkGa8rpJ5PPHQHKU1rgpn9jNW8zBuq4RWnOe9Ya13hSO6i8UUuMo8RkF1nmsb0HT7cKzi6mIqSOqEpBk9LKj+Zjrol5lRJT+ngUn55Ls2riYE5r+FgMjozWZQSefo672YGuKyqGOHIaWfWv8LuJaamSDN6qoIKbsC1EP8NEE9wl4TQ0BIlUD/g00+ZnlKFWKzYiA3nZ58HqJifNUdW7CjodkiboIOSeQKRb1KUZDvi7FxA/pjDEOymnB+eUg0aSjkM1bgnLn5/5LqvDpEof+0iNkPn+ovqwCOgk5FctYtPZ7qxqCiU6UjM7CNa2n6ESyreG/vy55mr6FFidmzbYDz5mVdIAWDS86FcDZAAzBYFIgl+vY=
